# This is a basic workflow to help you get started with Actions



name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]   # Runs when you push to main
  pull_request:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: docker build -t toscar8/portfolio:latest .
      - name: Push Docker image
        run: docker push toscar8/portfolio:latest


